families:
  resnet:
    - name: resnet50
      model: resnet50
      weights: ResNet50_Weights.DEFAULT
      type: official
    - name: resnet101
      model: resnet101
      weights: ResNet101_Weights.DEFAULT
      type: official
    - name: resnet152
      model: resnet152
      weights: ResNet152_Weights.DEFAULT
      type: official

  vit: # Vision Transformer
    - name: vit_b_16
      model: vit_b_16
      weights: ViT_B_16_Weights.DEFAULT
      type: official
    - name: vit_b_32
      model: vit_b_32
      weights: ViT_B_32_Weights.DEFAULT
      type: official
    - name: vit_l_16
      model: vit_l_16
      weights: ViT_L_16_Weights.DEFAULT
      type: official

  vgg:
    - name: vgg11
      model: vgg11
      weights: VGG11_Weights.DEFAULT
      type: official
    - name: vgg16
      model: vgg16
      weights: VGG16_Weights.DEFAULT
      type: official
    - name: vgg19
      model: vgg19
      weights: VGG19_Weights.DEFAULT
      type: official